package com.manteam.iwant2learn.training.sql;

public abstract class TrainingQueries {

	public static final String RETRIEVE_ALL_SUBJECTS = "select SUBJECT_NAME, "
			+ "SUBJECT_DESCRIPTION, " + "SUBJECT_WRITEUP from syb_subject";

	public static final String RETRIEVE_SUBJECT_DETAILS = "SELECT A.IDSYB_SUBJECT, A.SUBJECT_NAME, B.SYB_SUB_MODULE_ID, B.MODULE_NAME, C.SYB_SUB_SUBMODULE_ID, C.SUBMODULE_NAME "
			+ "FROM SYB_SUBJECT A, SYB_MODULE B, SYB_SUBMODULE C "
			+ "WHERE A.SUBJECT_NAME = ? "
			+ "AND B.MODULE_SUBJECT_REF = A.IDSYB_SUBJECT "
			+ "AND C.MODULE_REF = B.SYB_SUB_MODULE_ID ";

	public static final String RETRIEVE_QUESTIONS_SUBMOD = "SELECT D.SUBJECT_NAME, C.MODULE_NAME, B.SUBMODULE_NAME, B.SUBMODULE_DESC, A.QUESTION, A.QUES_IMG_NAME, A.QUES_IMG, A.QNO_YEAR_MARKS, "
			+ "A.ANSWER, A.ANSWER_IMG_NAME, A.ANSWER_IMG "
			+ "FROM EXAM_QUESTIONS A, SYB_SUBMODULE B, SYB_MODULE C, SYB_SUBJECT D "
			+ "WHERE     A.SUBMODULE_ID = B.SYB_SUB_SUBMODULE_ID "
			+ "AND (C.MODULE_NAME, B.SUBMODULE_NAME) IN ";

	public static final String RETRIEVE_QUESTIONS_REST = " AND B.MODULE_REF = C.SYB_SUB_MODULE_ID "
			+ "AND C.MODULE_SUBJECT_REF = D.IDSYB_SUBJECT "
			+ "AND D.SUBJECT_NAME = ?";

	public static final String GET_KEYWORD_FOR_SUBMODULES = "SELECT C.SUBMODULE_NAME, A.KEYWORD, A.QUANTITIES, A.SYMBOLS, A.UNITS, A.FORMULAE, A.DATA "
			+ " FROM SYB_KEYWORD A, SUB_KEYWORD_SUBMODULE_MAP B, SYB_SUBMODULE C, SYB_MODULE D, SYB_SUBJECT E"
			+ " WHERE C.SYB_SUB_SUBMODULE_ID = B.SUBMODULE_ID"
			+ " AND A.SYB_KEYWORD_ID = B.KEYWORD_ID"
			+ " AND C.SUBMODULE_NAME IN ";

	public static final String GET_KEYWORD_FOR_SUBMODULES_REST = " AND C.MODULE_REF = D.SYB_SUB_MODULE_ID "
			+ " AND D.MODULE_SUBJECT_REF = E.IDSYB_SUBJECT"
			+ " AND E.SUBJECT_NAME = ?";

}
