CREATE TABLE EXAM_QUES_SUBMODULE_MAP (
  EXAM_QUES_SUBMODULE_MAP_ID int(11) NOT NULL AUTO_INCREMENT,
  QUESTION_ID int(11) NOT NULL,
  SUBMODULE_ID int(11) NOT NULL,
  PRIMARY KEY (EXAM_QUES_SUBMODULE_MAP_ID),
  KEY QUESTION_ID_IDX (QUESTION_ID),
  KEY QUESTION_ID_REF (QUESTION_ID),
  KEY SUBMODULE_ID_REF (SUBMODULE_ID),
  CONSTRAINT QUESTION_ID_REF FOREIGN KEY (QUESTION_ID) REFERENCES exam_questions (EXAM_QUESTIONS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT SUBMODULE_ID_REF FOREIGN KEY (SUBMODULE_ID) REFERENCES syb_submodule (SYB_SUB_SUBMODULE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COMMENT='This table is intended to map the question id to submodule'

