CREATE TABLE IF NOT EXISTS SUB_KEYWORD_SUBMODULE_MAP (
  SUB_KEYWORD_SUBMODULE_MAP_ID int(11) NOT NULL,
  KEYWORD_ID int(11) NOT NULL,
  SUBMODULE_ID int(11) NOT NULL,
  PRIMARY KEY (SUB_KEYWORD_SUBMODULE_MAP_ID),
  KEY KEYWORD_SUBMOD_INDEX (KEYWORD_ID,SUBMODULE_ID),
  KEY KEYWORD_FK (KEYWORD_ID),
  KEY SUBMODULE_FK (SUBMODULE_ID),
  CONSTRAINT KEYWORD_FK FOREIGN KEY (KEYWORD_ID) REFERENCES syb_keyword (SYB_KEYWORD_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT SUBMODULE_FK FOREIGN KEY (SUBMODULE_ID) REFERENCES syb_submodule (SYB_SUB_SUBMODULE_ID) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1

